=head1 NAME

TicketSMSNotification

=head1 DESCRIPTION

This add on sends short messages to agents when a ticket is created. To use this, you need to install the Perl module C<Nexmo::SMS> and create
an account at L<http://nexmo.com>.

In the SysConfig you have to configure the account data.

The recipient of the messages can be configured by queue.

=head1 REPOSITORY & BUGTRACKER

The code repository and the bugtracker are available at L<http://github.com/reneeb/otrs-TicketSMSNotification>.

=head1 PRO-VERSION

There is a pro version of this module. The pro version allows you to use other providers than Nexmo.
You can find more information about the pro version at 
L<http://feature-addons.de/otrs/Misc%20Agent%20Tools/TicketSMSNotification>.

=head1 AUTHOR AND LICENSE

Renee Baecker E<lt>opar@perl-services.deE<gt>

License: AGPL 3
